spring.application.name=api-gateway

server.port=9000

#routes configuration
spring.cloud.gateway.server.webmvc.routes[0].id=CUSTOMER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.server.webmvc.routes[1].id=account-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://account-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/accounts/**

# Traditional MVC CircuitBreaker filter mapping
spring.cloud.gateway.server.webmvc.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.id=customerCircuitBreaker
spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.fallbackUri=forward:/fallback/customer-service

spring.cloud.gateway.server.webmvc.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[1].filters[0].args.id=accountCircuitBreaker
spring.cloud.gateway.server.webmvc.routes[1].filters[0].args.fallbackUri=forward:/fallback/account-service

# Resilience4j Configuration
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=5
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=15s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.sliding-window-type=count_based


# Specific config for account service (optional, overrides default)
resilience4j.circuitbreaker.instances.accountCircuitBreaker.baseConfig=default
resilience4j.circuitbreaker.instances.customerCircuitBreaker.baseConfig=default

#actuator
management.endpoints.web.exposure.include=*