spring.application.name=customer-service

server.port=9001

#config-client details
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=true

spring.datasource.url=jdbc:mysql://localhost:3306/customer_servicedb

#eureka.instance.hostname=localhost