spring.application.name=config-server

server.port=8888

#github-credentials
spring.cloud.config.server.git.uri=https://github.com/Rounak-007/bankapp-microservices-configurations
spring.cloud.config.server.git.clone-on-start=true

#spring.cloud.config.server.git.username = Rounak-007
#spring.cloud.config.server.git.password = Hellorounakdas@286199

spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_PASSWORD}
